import { useMemo } from 'react'
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, BrainCircuit, PiggyBank, Sparkles, Wallet } from 'lucide-react'
import StatCard from '../components/StatCard'
import BarChart from '../components/BarChart'
import { money, monthlySeries, summarize } from '../utils/finance'

export default function Dashboard({ transactions, profile, onAdd }) {
  const summary = useMemo(()=>summarize(transactions),[transactions])
  const series = useMemo(()=>monthlySeries(transactions),[transactions])
  const risk = summary.savingsRate < 0 ? 'Alto' : summary.savingsRate < 10 ? 'Medio' : 'Bajo'
  const profileLabel = profile?.perfil || profile?.perfilFinanciero || profile?.nivelRiesgo || 'En evaluación'
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Resumen financiero</span><h1>Tu dinero, de un vistazo</h1><p>Convierte tus movimientos en señales sencillas para decidir mejor.</p></div><button className="primary-button compact" onClick={onAdd}>+ Nueva transacción</button></div><div className="stats-grid"><StatCard icon={Wallet} label="Balance disponible" value={money(summary.balance)} hint={summary.balance>=0?'Saldo positivo':'Estás gastando más de lo que ingresas'} tone={summary.balance>=0?'positive':'negative'}/><StatCard icon={ArrowUpRight} label="Ingresos" value={money(summary.ingresos)} hint="Total registrado" tone="income"/><StatCard icon={ArrowDownLeft} label="Gastos" value={money(summary.gastos)} hint="Total registrado" tone="expense"/><StatCard icon={PiggyBank} label="Tasa de ahorro" value={`${summary.savingsRate}%`} hint={summary.topCategory?`Mayor gasto: ${summary.topCategory[0]}`:'Añade movimientos'} tone="saving"/></div><div className="content-grid"><section className="card chart-card"><div className="section-head"><div><h2>Flujo mensual</h2><p>Ingresos frente a gastos en los últimos meses registrados.</p></div><div className="legend"><span><i className="dot income"/>Ingresos</span><span><i className="dot expense"/>Gastos</span></div></div>{series.length?<BarChart data={series}/>:<div className="empty-state"><Sparkles size={28}/><strong>Aún no hay suficiente historial</strong><span>Registra algunas transacciones para empezar a ver tu evolución.</span></div>}</section><aside className="card insight-card"><div className="insight-top"><div className="ai-badge"><BrainCircuit size={19}/></div><span>Lectura inteligente</span></div><h2>{profileLabel}</h2><p>{summary.topCategory?`Tu categoría de mayor consumo es ${summary.topCategory[0]}, con ${money(summary.topCategory[1])} registrados.`:'Cuando acumules transacciones, CapitaXYZ identificará tus patrones de consumo.'}</p><div className={`risk-pill ${risk.toLowerCase()}`}><AlertTriangle size={15}/> Nivel de riesgo estimado: {risk}</div></aside></div><div className="card recommendation-banner"><div className="ai-badge"><Sparkles size={18}/></div><div><strong>La mejor recomendación empieza con datos consistentes.</strong><span>Registra tus movimientos con frecuencia para detectar hábitos positivos y señales de riesgo.</span></div><button className="secondary-button" onClick={onAdd}>Registrar gasto</button></div></div>
}
